import nbformat as nbf
import os

nb_path = '/home/zombie/Documents/Trading_Agent/deep_learning_backtest/Colab_Master_Pipeline.ipynb'

with open(nb_path, 'r', encoding='utf-8') as f:
    nb = nbf.read(f, as_version=4)

upload_cell_lstm = """# --- DATA CHECK: Ensure processed PKL exists for LSTM ---
import os
from pathlib import Path
try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

DATA_PROC = Path('.') / 'data' / 'processed'
DATA_PROC.mkdir(parents=True, exist_ok=True)

pkl_files = list(DATA_PROC.glob('*_processed.pkl'))
if not pkl_files:
    print("⚠️ No processed data (.pkl) found in data/processed/.")
    if IN_COLAB:
        print("Please upload your processed data file (e.g., SPY_processed.pkl):")
        uploaded = files.upload()
        for fn in uploaded.keys():
            os.rename(fn, DATA_PROC / fn)
            print(f"✅ Moved {fn} to {DATA_PROC}")
    else:
        print("Please ensure you have run the Data Pipeline steps above.")
else:
    print(f"✅ Found processed data: {[f.name for f in pkl_files]}")
"""

upload_cell_dqn = """# --- DATA CHECK: Ensure LSTM Probs exist for DQN ---
import os
from pathlib import Path
try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

DATA_PROC = Path('.') / 'data' / 'processed'
lstm_probs_path = DATA_PROC / 'lstm_test_probs.pkl'

if not lstm_probs_path.exists():
    print("⚠️ lstm_test_probs.pkl not found in data/processed/.")
    if IN_COLAB:
        print("Please upload lstm_test_probs.pkl (generated by the LSTM step):")
        uploaded = files.upload()
        for fn in uploaded.keys():
            if fn == 'lstm_test_probs.pkl':
                os.rename(fn, lstm_probs_path)
                print(f"✅ Moved {fn} to {DATA_PROC}")
    else:
        print("Please ensure you have run the LSTM training and inference steps above.")
else:
    print("✅ Found lstm_test_probs.pkl")
"""

new_cells = []
for cell in nb.cells:
    # Insert before LSTM section
    if cell.cell_type == 'markdown' and '03_lstm_model' in cell.source:
        new_cells.append(nbf.v4.new_code_cell(upload_cell_lstm))
    
    # Insert before DQN section
    if cell.cell_type == 'markdown' and '04_dqn_agent' in cell.source:
        new_cells.append(nbf.v4.new_code_cell(upload_cell_dqn))
        
    new_cells.append(cell)

nb.cells = new_cells

with open(nb_path, 'w', encoding='utf-8') as f:
    nbf.write(nb, f)

print("Added Colab upload checks.")
